### ISSUE TITLE
Cannot read property 'connections' of undefined at journeys.then

### ISSUE THREAD

**Issue by cmaxmedia** [mymro/oebb-api#7]
```
oebb.getJourneys(1140301, 1240820, true).then((res)=>{
callback({ data: res });
});
```

gives me a 
```
(node:3174477) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'connections' of undefined
    at journeys.then (/var/www/.sites/site21018389/html/test/oebb-api/oebb.js:278:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3174477) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3174477) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

node version v10.23.1
Any Ideas?
Cheers Markus

**Comment by lexao85** [comment]
the same issue. you can change `timetableUrl` in `oebb.js` (line 13) to:
`const timetableUrl = url.parse("https://shop.oebbtickets.at/api/hafas/v4/timetable");`
with changed url it works
